// Shared sessions store — backed by Supabase (`public.sessions` +
// `public.session_member_statuses` [normalized per-member status for group
// sessions] + `public.report_admin_edits` [append-only audit log]). Global
// cache hydrated once + Postgres Realtime, same pattern used across this
// migration. Writes stay optimistic-sync in their public signature (update
// cache + notify immediately, real round-trip in the background with
// rollback on failure) — there is no real race condition on sessions the
// way there was on club claims, so the simpler A3 pattern applies.
//
// Multi-row writes (a group session touching its own row + N per-member
// rows) go through the `upsert_session_member_statuses` RPC (one DB
// transaction) so Realtime never shows a half-updated group session — same
// rationale as `replace_teacher_availability` in availability-store.ts.
//
// KNOWN LIMITATION (documented, not fixed in this lote): RLS on
// `session_member_statuses` only lets a student see THEIR OWN row for a
// group session (admin/the session's teacher see all). `evaluateGroupUnanimity`
// therefore can't see other members' choices from a student's own cache, so
// unanimous-cancel/reschedule detection only works reliably for admin/teacher
// callers today. Not a regression for this beta — every real beta user is on
// an individual plan, no group sessions in play yet. Revisit once
// groups-store.ts (Tier B) is migrated and group plans go live for real users.
import { supabase } from "@/integrations/supabase/client";
import { registerRehydrate } from "@/lib/auth-rehydrate";
import type { Database } from "@/integrations/supabase/types";
import { hydrateUserIdBridge, legacyToUuid, uuidToLegacySync } from "@/lib/user-id-bridge";
import { setCoverageNote } from "./coverage-notes-store";
import { saveSubskillEvaluation } from "./performance-store";
import { decrementGroupRemaining, activeMembersOf } from "./groups-store";
import { adjustRemainingSessions } from "./students-store";
import { STATUS_PALETTE, statusTextColor } from "./status-palette";


export type ExtSessionStatus =
  | "scheduled"
  | "rescheduled"
  | "ready"
  | "rearranged"
  | "completed"
  | "absent"
  | "delayed"
  | "cancelled"
  | "pending_reschedule"
  | "no_show"
  // Student replaced this 1:1 with a Spotlight in the same slot. Not a strike,
  // not Cancelled, not Absent — its own status with its own indigo color.
  | "converted_to_spotlight";

// Optional refinement of an Absent or Cancelled status. All six sub-statuses
// count the session as accounted for but do NOT penalize attendance metrics
// (that's the whole point of a justification). They live alongside `status`
// so existing consumers keep working, and so a session can be Absent while
// still carrying "Absent Illness" context.
export type AttendanceSubStatus =
  | "absent_work"
  | "absent_illness"
  | "absent_vacation"
  | "cancelled_illness"
  | "cancelled_holiday"
  | "cancelled_work";

export interface ReportAdminEdit {
  at: string;
  actorId: string;
  actorName?: string;
  studentId?: string;
  field: "status" | "sub_status" | "member_status" | "member_sub_status";
  from: string;
  to: string;
  note?: string;
}

export interface ExtSession {
  id: string;
  student_id: string;
  teacher_id: string;
  date_time: string; // ISO
  duration_minutes: number;
  teams_link: string;
  status: ExtSessionStatus;
  absent_cause?: "student" | "teacher";
  report_pdf_url?: string;
  student_rating?: number;
  student_comment?: string;
  review_status?: "pending" | "reviewed" | "discarded";
  review_note?: string;
  notes?: string;
  attendance_delayed?: boolean;
  report_submitted_at?: string;
  origin?: "course" | "workshop" | "spotlight" | "group";
  workshop_cohort_id?: string;
  workshop_template_id?: string;
  workshop_topic?: string;
  group_id?: string;
  member_statuses?: Record<string, ExtSessionStatus>;
  member_absent_cause?: Record<string, "student" | "teacher">;
  /** Sub-status for the top-level Absent/Cancelled status (1:1 sessions). */
  attendance_sub_status?: AttendanceSubStatus;
  /** Per-member sub-status (group sessions). */
  member_sub_statuses?: Record<string, AttendanceSubStatus>;
  /** True once submitSessionReport / submitGroupSessionReport has run.
   *  Locks the teacher out of editing statuses; Admin can still amend. */
  report_locked?: boolean;
  /** Ordered audit trail of Admin edits after `report_locked` was set. */
  report_admin_edits?: ReportAdminEdit[];
  cancellation_reason?: "illness" | "personal" | "major_issue" | "other";
  cancellation_note?: string;
  needs_substitute?: boolean;
  /** True once a substitute teacher has been assigned to cover this session. */
  covered_by_substitute?: boolean;
  report_comments?: string;
  /** True only for sessions auto-generated by the Bulk Scheduler as a
   *  replacement for a date that landed on an official holiday. */
  holiday_makeup?: boolean;
}

export const SESSIONS_EVENT = "verbo:sessions-updated";

type SessionRow = Database["public"]["Tables"]["sessions"]["Row"];
type SessionInsert = Database["public"]["Tables"]["sessions"]["Insert"];
type SessionUpdate = Database["public"]["Tables"]["sessions"]["Update"];
type MemberStatusRow = Database["public"]["Tables"]["session_member_statuses"]["Row"];
type AdminEditRow = Database["public"]["Tables"]["report_admin_edits"]["Row"];

let sessionsCache: ExtSession[] = [];
let hydrated = false;
let hydratePromise: Promise<void> | null = null;
const listeners = new Set<() => void>();
const SSR_SNAPSHOT: ExtSession[] = [];

function notify() {
  listeners.forEach((cb) => cb());
  if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent(SESSIONS_EVENT));
}

function setSessionEntry(id: string, session: ExtSession | undefined, prepend?: ExtSession) {
  if (prepend) {
    sessionsCache = [prepend, ...sessionsCache];
    return;
  }
  if (session) {
    sessionsCache = sessionsCache.map((s) => (s.id === id ? session : s));
  } else {
    sessionsCache = sessionsCache.filter((s) => s.id !== id);
  }
}

function mapSessionRow(row: SessionRow, members: MemberStatusRow[], edits: AdminEditRow[]): ExtSession {
  const memberStatuses: Record<string, ExtSessionStatus> = {};
  const memberAbsentCause: Record<string, "student" | "teacher"> = {};
  const memberSubStatuses: Record<string, AttendanceSubStatus> = {};
  for (const m of members) {
    const legacyId = uuidToLegacySync(m.student_id);
    memberStatuses[legacyId] = m.status;
    if (m.absent_cause === "student" || m.absent_cause === "teacher") memberAbsentCause[legacyId] = m.absent_cause;
    if (m.attendance_sub_status) memberSubStatuses[legacyId] = m.attendance_sub_status;
  }
  const reportAdminEdits: ReportAdminEdit[] = edits
    .slice()
    .sort((a, b) => +new Date(a.at) - +new Date(b.at))
    .map((e) => ({
      at: e.at,
      actorId: uuidToLegacySync(e.actor_id),
      actorName: e.actor_name ?? undefined,
      studentId: e.student_id ? uuidToLegacySync(e.student_id) : undefined,
      field: e.field as ReportAdminEdit["field"],
      from: e.from_value,
      to: e.to_value,
      note: e.note ?? undefined,
    }));

  return {
    id: String(row.id),
    student_id: row.student_id ? uuidToLegacySync(row.student_id) : "",
    teacher_id: uuidToLegacySync(row.teacher_id),
    date_time: row.date_time,
    duration_minutes: row.duration_minutes,
    teams_link: row.teams_link,
    status: row.status,
    absent_cause: (row.absent_cause as "student" | "teacher" | null) ?? undefined,
    report_pdf_url: row.report_pdf_url ?? undefined,
    student_rating: row.student_rating ?? undefined,
    student_comment: row.student_comment ?? undefined,
    review_status: (row.review_status as ExtSession["review_status"]) ?? undefined,
    review_note: row.review_note ?? undefined,
    notes: row.notes ?? undefined,
    attendance_delayed: row.attendance_delayed ?? undefined,
    report_submitted_at: row.report_submitted_at ?? undefined,
    origin: row.origin ?? undefined,
    workshop_cohort_id: row.workshop_cohort_id !== null ? String(row.workshop_cohort_id) : undefined,
    workshop_template_id: row.workshop_template_id !== null ? String(row.workshop_template_id) : undefined,
    workshop_topic: row.workshop_topic ?? undefined,
    group_id: row.group_id !== null ? String(row.group_id) : undefined,
    attendance_sub_status: row.attendance_sub_status ?? undefined,
    report_locked: row.report_locked ?? undefined,
    cancellation_reason: row.cancellation_reason ?? undefined,
    cancellation_note: row.cancellation_note ?? undefined,
    needs_substitute: row.needs_substitute ?? undefined,
    covered_by_substitute: row.covered_by_substitute ?? undefined,
    report_comments: row.report_comments ?? undefined,
    holiday_makeup: row.holiday_makeup ?? undefined,
    member_statuses: Object.keys(memberStatuses).length ? memberStatuses : undefined,
    member_absent_cause: Object.keys(memberAbsentCause).length ? memberAbsentCause : undefined,
    member_sub_statuses: Object.keys(memberSubStatuses).length ? memberSubStatuses : undefined,
    report_admin_edits: reportAdminEdits.length ? reportAdminEdits : undefined,
  };
}

async function hydrate(): Promise<void> {
  if (hydrated) return;
  if (hydratePromise) return hydratePromise;
  hydratePromise = (async () => {
    await hydrateUserIdBridge();
    const [sessionsRes, membersRes, editsRes] = await Promise.all([
      supabase.from("sessions").select("*"),
      supabase.from("session_member_statuses").select("*"),
      supabase.from("report_admin_edits").select("*"),
    ]);
    if (sessionsRes.error) console.error("[sessions-store] failed to load sessions", sessionsRes.error);
    if (membersRes.error) console.error("[sessions-store] failed to load session_member_statuses", membersRes.error);
    if (editsRes.error) console.error("[sessions-store] failed to load report_admin_edits", editsRes.error);

    const membersBySession = new Map<number, MemberStatusRow[]>();
    for (const m of (membersRes.data ?? []) as MemberStatusRow[]) {
      const list = membersBySession.get(m.session_id) ?? [];
      list.push(m);
      membersBySession.set(m.session_id, list);
    }
    const editsBySession = new Map<number, AdminEditRow[]>();
    for (const e of (editsRes.data ?? []) as AdminEditRow[]) {
      const list = editsBySession.get(e.session_id) ?? [];
      list.push(e);
      editsBySession.set(e.session_id, list);
    }

    sessionsCache = ((sessionsRes.data ?? []) as SessionRow[]).map((row) =>
      mapSessionRow(row, membersBySession.get(row.id) ?? [], editsBySession.get(row.id) ?? []),
    );
    hydrated = true;
  })();
  await hydratePromise;
  hydratePromise = null;
  notify();
}

function invalidateAndRehydrate() {
  hydrated = false;
  hydratePromise = null;
  void hydrate();
}

if (typeof window !== "undefined") {
  void hydrate();
  supabase
    .channel("sessions-changes")
    .on("postgres_changes", { event: "*", schema: "public", table: "sessions" }, () => {
      hydrated = false;
      void hydrate();
    })
    .subscribe();
  supabase
    .channel("session-member-statuses-changes")
    .on("postgres_changes", { event: "*", schema: "public", table: "session_member_statuses" }, () => {
      hydrated = false;
      void hydrate();
    })
    .subscribe();
  supabase
    .channel("report-admin-edits-changes")
    .on("postgres_changes", { event: "*", schema: "public", table: "report_admin_edits" }, () => {
      hydrated = false;
      void hydrate();
    })
    .subscribe();
  registerRehydrate(invalidateAndRehydrate);}

export function loadSessions(): ExtSession[] {
  if (!hydrated) void hydrate();
  return sessionsCache;
}

export function getSessionsSnapshot(): ExtSession[] {
  if (!hydrated) void hydrate();
  return sessionsCache;
}

export function getServerSessionsSnapshot(): ExtSession[] {
  return SSR_SNAPSHOT;
}

export function subscribeSessions(cb: () => void): () => void {
  listeners.add(cb);
  return () => {
    listeners.delete(cb);
  };
}

/** All sessions that belong to a given Focus Workshop cohort. */
export function sessionsForCohort(cohortId: string): ExtSession[] {
  return loadSessions().filter(
    (s) => s.origin === "workshop" && s.workshop_cohort_id === cohortId,
  );
}

/** Generic "insert one new session row" — replaces the old localStorage
 *  `persistSessions(fullArray)` pattern (Supabase has no cheap "replace the
 *  whole table" primitive). Optimistic: returns a client-side session
 *  immediately (temp id), the real insert + id swap happen in the
 *  background. */
function createSessionInternal(input: Partial<ExtSession> & {
  student_id: string;
  teacher_id: string;
  date_time: string;
  duration_minutes: number;
  teams_link: string;
}): ExtSession {
  const tempId = `temp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const optimistic: ExtSession = {
    status: "scheduled",
    ...input,
    id: tempId,
  };
  sessionsCache = [optimistic, ...sessionsCache];
  notify();

  void (async () => {
    const [studentUuid, teacherUuid] = await Promise.all([
      input.student_id ? legacyToUuid(input.student_id) : Promise.resolve(null),
      legacyToUuid(input.teacher_id),
    ]);
    if (!teacherUuid) {
      console.error("[sessions-store] unknown teacher id, dropping optimistic session", input.teacher_id);
      sessionsCache = sessionsCache.filter((s) => s.id !== tempId);
      notify();
      return;
    }
    const insert: SessionInsert = {
      student_id: studentUuid,
      teacher_id: teacherUuid,
      date_time: input.date_time,
      duration_minutes: input.duration_minutes,
      teams_link: input.teams_link,
      status: input.status ?? "scheduled",
      origin: input.origin,
      notes: input.notes ?? null,
      group_id: input.group_id ? Number(input.group_id) : null,
      workshop_cohort_id: input.workshop_cohort_id ? Number(input.workshop_cohort_id) : null,
      workshop_template_id: input.workshop_template_id ? Number(input.workshop_template_id) : null,
      workshop_topic: input.workshop_topic ?? null,
    };
    const { data, error } = await supabase.from("sessions").insert(insert).select("*").single();
    if (error || !data) {
      console.error("[sessions-store] failed to create session", error);
      sessionsCache = sessionsCache.filter((s) => s.id !== tempId);
      notify();
      return;
    }
    const created = mapSessionRow(data, [], []);
    sessionsCache = sessionsCache.map((s) => (s.id === tempId ? created : s));
    notify();
  })();

  return optimistic;
}

/** Public wrapper around `createSessionInternal` — the replacement for the
 *  old localStorage-era `persistSessions(fullArray)` escape hatch. Any
 *  caller (e.g. student-requests-store's claim/spotlight-conversion flows)
 *  that needs to materialize a brand-new session should use this instead of
 *  reaching into the cache directly. */
export function createSession(input: Partial<ExtSession> & {
  student_id: string;
  teacher_id: string;
  date_time: string;
  duration_minutes: number;
  teams_link: string;
}): ExtSession {
  return createSessionInternal(input);
}

/** Adds one workshop session record to the shared sessions store. */
export function addWorkshopSession(input: {
  cohortId: string;
  templateId: string;
  teacherId: string;
  teamsLink: string;
  dateISO?: string;
  durationMinutes?: number;
  topic?: string;
}): ExtSession {
  return createSessionInternal({
    student_id: input.cohortId, // sentinel; workshop cohorts hold the roster
    teacher_id: input.teacherId,
    date_time: input.dateISO ?? "",
    duration_minutes: input.durationMinutes ?? 60,
    teams_link: input.teamsLink,
    status: "scheduled",
    origin: "workshop",
    workshop_cohort_id: input.cohortId,
    workshop_template_id: input.templateId,
    workshop_topic: input.topic,
  });
}

/** Create one Performance Session for a Group. Mirrors `addWorkshopSession`:
 *  `student_id` is a sentinel (any active roster member id) so surfaces that
 *  resolve group membership via `groupsByStudentId()` still work, while
 *  `group_id` is the real link.
 *
 *  NOTE: no beta user is on a group plan yet — `group_id` must resolve to a
 *  real row in `public.groups`, which requires `groups-store.ts` (still on
 *  localStorage) to hand out real ids. Until that's migrated, calling this
 *  with a legacy/mock group id will fail the FK and return null — implemented
 *  correctly against the real schema, just not exercisable end-to-end yet. */
export function addGroupSession(input: {
  groupId: string;
  teacherId: string;
  teamsLink: string;
  dateISO?: string;
  durationMinutes?: number;
}): ExtSession | null {
  const roster = activeMembersOf(input.groupId);
  if (roster.length === 0) return null;
  const memberIds = roster.map((m) => m.student_id);
  const session = createSessionInternal({
    student_id: roster[0].student_id, // sentinel; the roster lives in Group
    group_id: input.groupId,
    teacher_id: input.teacherId,
    date_time: input.dateISO ?? "",
    duration_minutes: input.durationMinutes ?? 60,
    teams_link: input.teamsLink,
    status: "scheduled",
  });
  // member_statuses seeded to "scheduled" for every active member, so
  // studentCalendarEvents (which matches by student_id AND member_statuses
  // keys) shows the class immediately, before any Session Report exists.
  void (async () => {
    // Give createSessionInternal's background insert a moment to land so we
    // have a real numeric session id to attach member rows to.
    for (let i = 0; i < 20 && sessionsCache.find((s) => s.id === session.id); i++) {
      await new Promise((r) => setTimeout(r, 150));
    }
    const real = sessionsCache.find(
      (s) => s.group_id === input.groupId && s.date_time === (input.dateISO ?? "") && s.teacher_id === input.teacherId,
    );
    if (!real || !Number.isFinite(Number(real.id))) return;
    await upsertMemberStatuses({
      sessionId: real.id,
      members: memberIds.map((id) => ({ studentId: id, status: "scheduled" as ExtSessionStatus })),
    });
  })();
  return session;
}

export function updateWorkshopSession(id: string, patch: Partial<ExtSession>) {
  updateSession(id, patch);
}

export function removeWorkshopSession(id: string) {
  const prev = sessionsCache;
  sessionsCache = sessionsCache.filter((s) => s.id !== id);
  notify();
  const numericId = Number(id);
  if (!Number.isFinite(numericId)) return;
  void (async () => {
    const { error } = await supabase.from("sessions").delete().eq("id", numericId);
    if (error) {
      console.error("[sessions-store] failed to remove workshop session", error);
      sessionsCache = prev;
      notify();
    }
  })();
}

/** Background helper backing the multi-row RPC. Not exported — internal
 *  writes route through here; callers get the optimistic cache update
 *  synchronously via their own function, this just fires the real DB call. */
async function upsertMemberStatuses(input: {
  sessionId: string;
  setTopStatus?: ExtSessionStatus;
  setReportLocked?: boolean;
  reportSubmittedAt?: string;
  members: Array<{ studentId: string; status: ExtSessionStatus; absentCause?: "student" | "teacher"; subStatus?: AttendanceSubStatus | null }>;
}): Promise<boolean> {
  const numericId = Number(input.sessionId);
  if (!Number.isFinite(numericId)) return false;
  const membersPayload = await Promise.all(
    input.members.map(async (m) => ({
      studentId: await legacyToUuid(m.studentId),
      status: m.status,
      absentCause: m.absentCause ?? "",
      subStatus: m.subStatus ?? "",
    })),
  );
  if (membersPayload.some((m) => !m.studentId)) {
    console.error("[sessions-store] unknown student id in member_statuses payload");
    return false;
  }
  const { error } = await supabase.rpc("upsert_session_member_statuses", {
    p_session_id: numericId,
    p_set_top_status: input.setTopStatus !== undefined,
    p_top_status: input.setTopStatus ?? "scheduled",
    p_set_report_locked: input.setReportLocked !== undefined,
    p_report_locked: input.setReportLocked ?? false,
    // Runtime-nullable (the SQL function does `if ... or p_report_submitted_at
    // is not null` and only touches the column when it's actually provided),
    // but Supabase's codegen can't see that from a plain `timestamptz` param
    // and generates a non-null Args type — hence the cast.
    p_report_submitted_at: (input.reportSubmittedAt ?? null) as unknown as string,
    p_members: membersPayload,
  });
  if (error) {
    console.error("[sessions-store] upsert_session_member_statuses failed", error);
    return false;
  }
  return true;
}

/** Generic patcher — used by Lesson Plan (→ Ready) and by any other
 *  surface that needs to update a single session while keeping every
 *  consumer live-synced. A `member_statuses` key in the patch is treated as
 *  the FULL desired per-member map (matching the caller convention already
 *  in place, e.g. CancelSessionFlow spreads the previous map + one changed
 *  key) — every entry present gets upserted into `session_member_statuses`
 *  via the atomic RPC; entries removed from the map are NOT deleted (no
 *  caller relies on removal, only on adding/changing one member at a time). */
export function updateSession(id: string, patch: Partial<ExtSession>) {
  const prev = sessionsCache.find((s) => s.id === id);
  if (!prev) return;
  const next: ExtSession = { ...prev, ...patch };
  sessionsCache = sessionsCache.map((s) => (s.id === id ? next : s));
  notify();

  const numericId = Number(id);
  if (!Number.isFinite(numericId)) return;

  if (patch.member_statuses) {
    const members = Object.entries(patch.member_statuses).map(([studentId, status]) => ({
      studentId,
      status,
      absentCause: patch.member_absent_cause?.[studentId],
      subStatus: patch.member_sub_statuses?.[studentId],
    }));
    void upsertMemberStatuses({ sessionId: id, members }).then((ok) => {
      if (!ok) {
        sessionsCache = sessionsCache.map((s) => (s.id === id ? prev : s));
        notify();
      }
    });
    // member_statuses can arrive alongside a top-level status change too
    // (rare, but keep both effects consistent) — fall through to the plain
    // update below for every OTHER field in the patch.
  }

  const update: SessionUpdate = {};
  if (patch.status !== undefined) update.status = patch.status;
  if (patch.date_time !== undefined) update.date_time = patch.date_time;
  if (patch.duration_minutes !== undefined) update.duration_minutes = patch.duration_minutes;
  if (patch.teams_link !== undefined) update.teams_link = patch.teams_link;
  if (patch.notes !== undefined) update.notes = patch.notes ?? null;
  if (patch.absent_cause !== undefined) update.absent_cause = patch.absent_cause ?? null;
  if (patch.report_pdf_url !== undefined) update.report_pdf_url = patch.report_pdf_url ?? null;
  if (patch.student_rating !== undefined) update.student_rating = patch.student_rating ?? null;
  if (patch.student_comment !== undefined) update.student_comment = patch.student_comment ?? null;
  if (patch.review_status !== undefined) update.review_status = patch.review_status ?? null;
  if (patch.review_note !== undefined) update.review_note = patch.review_note ?? null;
  if (patch.attendance_delayed !== undefined) update.attendance_delayed = patch.attendance_delayed ?? null;
  if (patch.report_submitted_at !== undefined) update.report_submitted_at = patch.report_submitted_at ?? null;
  if (patch.attendance_sub_status !== undefined) update.attendance_sub_status = patch.attendance_sub_status ?? null;
  if (patch.report_locked !== undefined) update.report_locked = patch.report_locked ?? null;
  if (patch.cancellation_reason !== undefined) update.cancellation_reason = patch.cancellation_reason ?? null;
  if (patch.cancellation_note !== undefined) update.cancellation_note = patch.cancellation_note ?? null;
  if (patch.needs_substitute !== undefined) update.needs_substitute = patch.needs_substitute ?? null;
  if (patch.covered_by_substitute !== undefined) update.covered_by_substitute = patch.covered_by_substitute ?? null;
  if (patch.report_comments !== undefined) update.report_comments = patch.report_comments ?? null;
  if (patch.holiday_makeup !== undefined) update.holiday_makeup = patch.holiday_makeup ?? null;
  if (patch.workshop_topic !== undefined) update.workshop_topic = patch.workshop_topic ?? null;
  if ("teacher_id" in patch && patch.teacher_id) {
    void (async () => {
      const teacherUuid = await legacyToUuid(patch.teacher_id!);
      if (!teacherUuid) return;
      const { error } = await supabase.from("sessions").update({ teacher_id: teacherUuid }).eq("id", numericId);
      if (error) console.error("[sessions-store] failed to update teacher_id", error);
    })();
  }

  if (Object.keys(update).length === 0) return;
  void (async () => {
    const { error } = await supabase.from("sessions").update(update).eq("id", numericId);
    if (error) {
      console.error("[sessions-store] failed to update session", error);
      sessionsCache = sessionsCache.map((s) => (s.id === id ? prev : s));
      notify();
    }
  })();
}

/** Persist a student's rating for a completed session. Ratings of 3★ or
 *  below flip `review_status` to "pending" so the session enters the
 *  Flagged Reviews queue in Admin > Teachers. Higher ratings leave
 *  `review_status` untouched. */
export function submitStudentRating(sessionId: string, rating: number, comment?: string) {
  const patch: Partial<ExtSession> = { student_rating: rating };
  if (comment !== undefined) patch.student_comment = comment;
  if (rating <= 3) patch.review_status = "pending";
  updateSession(sessionId, patch);
}

/** Final Session Report submit. Single source of truth for the four
 *  effects the spec requires:
 *    1. Session → Completed (Present/Delayed) or Absent (with cause).
 *    2. Attendance metadata (delayed flag).
 *    3. Real per-subskill scores flow into the same performance store
 *       the student dashboard + Teacher > Mis Alumnos read from.
 *    4. Any coverage note for (teacher, student) is cleared.
 *
 *  Not handled here on purpose: PDF generation and email dispatch.
 */
export function submitSessionReport(input: {
  sessionId: string;
  teacherId: string;
  studentId: string;
  attendance: "present" | "delayed" | "absent";
  absentCause?: "student" | "teacher";
  subStatus?: AttendanceSubStatus | null;
  subskills: Record<string, number>;
  reportComments?: string;
  /** Required "Class notes" write-up from the report form. Previously this
   *  was only ever baked into the generated PDF and never persisted to a
   *  queryable column — Admin had no way to see it without opening the PDF.
   *  Now saved to `sessions.notes` alongside everything else. */
  notes?: string;
}): ExtSession | null {
  const prev = sessionsCache.find((s) => s.id === input.sessionId);
  if (!prev) return null;
  const status: ExtSessionStatus = input.attendance === "absent" ? "absent" : "completed";
  const patch: Partial<ExtSession> = {
    status,
    absent_cause: status === "absent" ? (input.absentCause ?? "student") : undefined,
    attendance_delayed: input.attendance === "delayed",
    attendance_sub_status: status === "absent" && input.subStatus ? input.subStatus : undefined,
    report_submitted_at: new Date().toISOString(),
    report_locked: true,
    report_comments: input.reportComments?.trim() ? input.reportComments.trim() : prev.report_comments,
    notes: input.notes?.trim() ? input.notes.trim() : prev.notes,
  };
  updateSession(input.sessionId, patch);

  if (status !== "absent" && Object.keys(input.subskills).length > 0) {
    saveSubskillEvaluation(input.sessionId, input.studentId, input.teacherId, input.subskills);
  }
  setCoverageNote(input.teacherId, input.studentId, "");

  // Decrement remaining_sessions for 1:1 individual sessions when the class
  // actually occurred. Mirrors the group-side rule in submitGroupSessionReport.
  const isOneOnOne = !prev.origin && !prev.group_id && !prev.workshop_cohort_id && !prev.workshop_template_id;
  const classOccurred = !(status === "absent" && input.absentCause === "teacher");
  if (isOneOnOne && classOccurred) {
    adjustRemainingSessions(input.studentId, -1);
  }
  return { ...prev, ...patch };
}

// -----------------------------------------------------------------------------
// Group Session Report — one shared class, per-member attendance & evaluation.
// -----------------------------------------------------------------------------
export function submitGroupSessionReport(input: {
  sessionId: string;
  teacherId: string;
  groupId: string;
  perMember: Array<{
    studentId: string;
    attendance: "present" | "delayed" | "absent";
    absentCause?: "student" | "teacher";
    subStatus?: AttendanceSubStatus | null;
    subskills: Record<string, number>;
  }>;
}): ExtSession | null {
  const prev = sessionsCache.find((s) => s.id === input.sessionId);
  if (!prev) return null;

  const memberStatuses: Record<string, ExtSessionStatus> = { ...(prev.member_statuses ?? {}) };
  const memberAbsentCause: Record<string, "student" | "teacher"> = { ...(prev.member_absent_cause ?? {}) };
  const memberSubStatuses: Record<string, AttendanceSubStatus> = { ...(prev.member_sub_statuses ?? {}) };
  for (const m of input.perMember) {
    memberStatuses[m.studentId] = m.attendance === "absent" ? "absent" : "completed";
    if (m.attendance === "absent") memberAbsentCause[m.studentId] = m.absentCause ?? "student";
    if (m.attendance === "absent" && m.subStatus) memberSubStatuses[m.studentId] = m.subStatus;
  }
  const anyPresent = input.perMember.some((m) => m.attendance !== "absent");
  const nextTop: ExtSessionStatus = anyPresent ? "completed" : "absent";
  const reportSubmittedAt = new Date().toISOString();

  const optimistic: ExtSession = {
    ...prev,
    status: nextTop,
    member_statuses: memberStatuses,
    member_absent_cause: memberAbsentCause,
    member_sub_statuses: memberSubStatuses,
    report_submitted_at: reportSubmittedAt,
    report_locked: true,
  };
  sessionsCache = sessionsCache.map((s) => (s.id === input.sessionId ? optimistic : s));
  notify();

  void upsertMemberStatuses({
    sessionId: input.sessionId,
    setTopStatus: nextTop,
    setReportLocked: true,
    reportSubmittedAt,
    members: input.perMember.map((m) => ({
      studentId: m.studentId,
      status: m.attendance === "absent" ? "absent" : "completed",
      absentCause: m.attendance === "absent" ? (m.absentCause ?? "student") : undefined,
      subStatus: m.attendance === "absent" ? m.subStatus : undefined,
    })),
  }).then((ok) => {
    if (!ok) {
      sessionsCache = sessionsCache.map((s) => (s.id === input.sessionId ? prev : s));
      notify();
    }
  });

  for (const m of input.perMember) {
    if (m.attendance !== "absent" && Object.keys(m.subskills).length > 0) {
      saveSubskillEvaluation(input.sessionId, m.studentId, input.teacherId, m.subskills);
    }
    setCoverageNote(input.teacherId, m.studentId, "");
  }

  // Group progress advances exactly once (not per member), and only when the
  // class actually took place.
  const classOccurred = input.perMember.some(
    (m) => m.attendance !== "absent" || (m.absentCause ?? "student") === "student",
  );
  if (classOccurred) decrementGroupRemaining(input.groupId);

  return optimistic;
}

// -----------------------------------------------------------------------------
// Group Session Unanimity — Can't Attend flow.
// -----------------------------------------------------------------------------
export type GroupUnanimityOutcome =
  | { kind: "none" }
  | { kind: "unanimous_cancel" }
  | { kind: "unanimous_reschedule" };

/** Pure evaluator — returns what the top-level status *should* be given the
 *  current member_statuses map. Does not mutate. See file-header note: for a
 *  non-admin/non-teacher caller, `session.member_statuses` may only contain
 *  their own entry (RLS), so unanimity can under-detect for students today. */
export function evaluateGroupUnanimity(
  session: ExtSession,
  overrideMemberStatuses?: Record<string, ExtSessionStatus>,
): GroupUnanimityOutcome {
  if (!session.group_id) return { kind: "none" };
  const memberStatuses = overrideMemberStatuses ?? session.member_statuses ?? {};
  const rosterIds = activeMembersOf(session.group_id).map((m) => m.student_id);
  if (rosterIds.length === 0) return { kind: "none" };
  const values = rosterIds.map((id) => memberStatuses[id]);
  if (values.every((v) => v === "cancelled")) return { kind: "unanimous_cancel" };
  if (values.every((v) => v === "pending_reschedule")) return { kind: "unanimous_reschedule" };
  return { kind: "none" };
}

/** Applies a per-member cancel or reschedule to a group session and evaluates
 *  strict unanimity. Returns the outcome so the caller can toast / trigger a
 *  group-level Reschedule Request when unanimity flips top-level state. */
export function applyGroupMemberCancellation(
  sessionId: string,
  studentId: string,
  memberStatus: "cancelled" | "pending_reschedule",
): { outcome: GroupUnanimityOutcome; topStatus: ExtSessionStatus } {
  const sess = sessionsCache.find((s) => s.id === sessionId);
  if (!sess || !sess.group_id) {
    updateSession(sessionId, { status: memberStatus });
    return { outcome: { kind: "none" }, topStatus: memberStatus };
  }

  const nextMemberStatuses: Record<string, ExtSessionStatus> = {
    ...(sess.member_statuses ?? {}),
    [studentId]: memberStatus,
  };
  const outcome = evaluateGroupUnanimity(sess, nextMemberStatuses);
  const patch: Partial<ExtSession> = { member_statuses: nextMemberStatuses };
  if (outcome.kind === "unanimous_cancel") patch.status = "cancelled";
  else if (outcome.kind === "unanimous_reschedule") patch.status = "pending_reschedule";
  updateSession(sessionId, patch);
  return {
    outcome,
    topStatus: (patch.status ?? sess.status) as ExtSessionStatus,
  };
}

// -----------------------------------------------------------------------------
// Admin overrides after a Session Report is locked. No current call sites in
// the app (prepared for a future Admin UI) — implemented against the real
// schema (INSERT-only `report_admin_edits`, matching its append-only RLS).
// -----------------------------------------------------------------------------
export function adminAmendSession(
  sessionId: string,
  actor: { id: string; name?: string },
  edit: {
    studentId?: string;
    field: ReportAdminEdit["field"];
    to: string;
    note?: string;
  },
): ExtSession | null {
  const s = sessionsCache.find((x) => x.id === sessionId);
  if (!s) return null;

  let from = "";
  const patch: Partial<ExtSession> = {};
  if (edit.field === "status") {
    from = s.status;
    patch.status = edit.to as ExtSessionStatus;
  } else if (edit.field === "sub_status") {
    from = s.attendance_sub_status ?? "";
    patch.attendance_sub_status = (edit.to || undefined) as AttendanceSubStatus | undefined;
  } else if (edit.field === "member_status" && edit.studentId) {
    from = s.member_statuses?.[edit.studentId] ?? "";
    patch.member_statuses = { ...(s.member_statuses ?? {}), [edit.studentId]: edit.to as ExtSessionStatus };
  } else if (edit.field === "member_sub_status" && edit.studentId) {
    from = s.member_sub_statuses?.[edit.studentId] ?? "";
    const map = { ...(s.member_sub_statuses ?? {}) };
    if (edit.to) map[edit.studentId] = edit.to as AttendanceSubStatus;
    else delete map[edit.studentId];
    patch.member_sub_statuses = map;
  } else {
    return s;
  }

  const auditEntry: ReportAdminEdit = {
    at: new Date().toISOString(),
    actorId: actor.id,
    actorName: actor.name,
    studentId: edit.studentId,
    field: edit.field,
    from,
    to: edit.to,
    note: edit.note,
  };
  const optimistic: ExtSession = {
    ...s,
    ...patch,
    report_admin_edits: [...(s.report_admin_edits ?? []), auditEntry],
  };
  sessionsCache = sessionsCache.map((x) => (x.id === sessionId ? optimistic : x));
  notify();

  updateSession(sessionId, patch);

  const numericId = Number(sessionId);
  if (Number.isFinite(numericId)) {
    void (async () => {
      const actorUuid = await legacyToUuid(actor.id);
      const studentUuid = edit.studentId ? await legacyToUuid(edit.studentId) : null;
      if (!actorUuid) return;
      const { error } = await supabase.from("report_admin_edits").insert({
        session_id: numericId,
        actor_id: actorUuid,
        actor_name: actor.name ?? null,
        student_id: studentUuid,
        field: edit.field,
        from_value: from,
        to_value: edit.to,
        note: edit.note ?? null,
      });
      if (error) console.error("[sessions-store] failed to record admin edit", error);
    })();
  }

  return optimistic;
}

// -----------------------------------------------------------------------------
// Sub-status meta (labels, initials, palette, month-end justification window).
// -----------------------------------------------------------------------------
export const SUB_STATUS_META: Record<
  AttendanceSubStatus,
  { label: string; initials: string; parent: "absent" | "cancelled"; color: string }
> = {
  absent_work:       { label: "Absent Work",       initials: "AW", parent: "absent",    color: "#ea580c" },
  absent_illness:    { label: "Absent Illness",    initials: "AI", parent: "absent",    color: "#ea580c" },
  absent_vacation:   { label: "Absent Vacation",   initials: "AV", parent: "absent",    color: "#ea580c" },
  cancelled_illness: { label: "Cancelled Illness", initials: "CI", parent: "cancelled", color: "#cbd5e1" },
  cancelled_holiday: { label: "Cancelled Holiday", initials: "CH", parent: "cancelled", color: "#0891b2" },
  cancelled_work:    { label: "Cancelled Work",    initials: "CW", parent: "cancelled", color: "#cbd5e1" },
};

/** Sub-status justifications can only be applied or edited while the session's
 *  month is still open (until the last calendar day of that month). Admin
 *  overrides via `adminAmendSession` bypass this rule. */
export function isJustificationWindowOpen(sessionDateISO: string, now: Date = new Date()): boolean {
  const d = new Date(sessionDateISO);
  const lastDay = new Date(d.getFullYear(), d.getMonth() + 1, 0, 23, 59, 59, 999);
  return now.getTime() <= lastDay.getTime();
}

/** Cascade update: when a cohort's teacher or shared link changes, keep
 *  future/non-completed sessions in sync so admin.sessions and the cohort
 *  view stay consistent without manual re-entry. */
export function syncCohortFieldsToSessions(
  cohortId: string,
  patch: { teacher_id?: string; teams_link?: string },
) {
  for (const s of sessionsCache) {
    if (s.origin !== "workshop" || s.workshop_cohort_id !== cohortId) continue;
    if (s.status === "completed" || s.status === "absent" || s.status === "no_show") continue;
    updateSession(s.id, patch);
  }
}

/** Derived from the single status palette so the Workshop badges can never
 *  drift from the calendar / dashboard colors again. */
export const WORKSHOP_STATUS_META: Record<
  ExtSessionStatus,
  { label: string; bg: string; color: string }
> = Object.fromEntries(
  (Object.keys(STATUS_PALETTE) as Array<keyof typeof STATUS_PALETTE>).map((k) => [
    k,
    { label: STATUS_PALETTE[k].label, bg: STATUS_PALETTE[k].color, color: statusTextColor(k) },
  ]),
) as Record<ExtSessionStatus, { label: string; bg: string; color: string }>;

export const WORKSHOP_STATUS_OPTIONS: ExtSessionStatus[] = [
  "scheduled", "ready", "completed", "absent", "cancelled", "pending_reschedule", "no_show",
];

export function statusTone(s: ExtSessionStatus): "default" | "success" | "warning" | "danger" | "muted" {
  switch (s) {
    case "completed": return "success";
    case "absent":
    case "no_show": return "danger";
    case "delayed":
    case "pending_reschedule": return "warning";
    case "ready": return "default";
    default: return "muted"; // scheduled / rescheduled / rearranged / cancelled
  }
}

// ---------------------------------------------------------------------------
// Attendance — single shared source of truth for the "% of sessions attended"
// metric.
// ---------------------------------------------------------------------------
export interface StudentAttendanceSummary {
  completed: number;
  absent: number;
  pct: number;
}

export const ATTENDANCE_WINDOW_DAYS = 90;

export function studentAttendance(
  sessions: Array<{ student_id: string; status: string; date_time?: string }>,
  student: { id: string; attendance_percentage?: number },
): StudentAttendanceSummary {
  const cutoff = Date.now() - ATTENDANCE_WINDOW_DAYS * 86_400_000;
  const rows = sessions.filter((s) => {
    if (s.student_id !== student.id) return false;
    const t = s.date_time ? new Date(s.date_time).getTime() : NaN;
    return Number.isFinite(t) ? t >= cutoff && t <= Date.now() : false;
  });
  const completed = rows.filter((s) => s.status === "completed").length;
  const absent = rows.filter((s) => s.status === "absent").length;
  const total = completed + absent;
  const pct = student.attendance_percentage ?? (total > 0 ? Math.round((completed / total) * 100) : 0);
  return { completed, absent, pct };
}

// ---------------------------------------------------------------------------
// Latest teacher report snippet for a student.
// ---------------------------------------------------------------------------
export function lastCoveredSummaryFor(
  sessions: Array<{ student_id: string; status: string; date_time: string; report_comments?: string }>,
  studentId: string,
): string | undefined {
  const rows = sessions
    .filter((s) => s.student_id === studentId && s.status === "completed" && s.report_comments?.trim())
    .sort((a, b) => +new Date(b.date_time) - +new Date(a.date_time));
  const text = rows[0]?.report_comments?.trim();
  if (!text) return undefined;
  return text.length > 140 ? text.slice(0, 140).trim() + "…" : text;
}
