-- Published club catalog curation and student proposals. No seeded clubs.
alter table public.clubs
  add column if not exists catalog_featured boolean not null default false;

create table if not exists public.club_suggestions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.app_users(id) on delete cascade,
  type public.club_type not null,
  title text not null check (char_length(btrim(title)) between 3 and 160),
  details text not null default '' check (char_length(details) <= 2000),
  status text not null default 'new' check (status in ('new', 'reviewed', 'planned', 'closed')),
  created_at timestamptz not null default now()
);
create index if not exists club_suggestions_status_created_idx
  on public.club_suggestions (status, created_at desc);
alter table public.club_suggestions enable row level security;
grant select, insert, update on public.club_suggestions to authenticated;
create policy club_suggestions_select on public.club_suggestions for select to authenticated
  using (student_id = (select auth.uid()) or private.is_admin());
create policy club_suggestions_insert on public.club_suggestions for insert to authenticated
  with check (student_id = (select auth.uid()) and status = 'new');
create policy club_suggestions_admin_update on public.club_suggestions for update to authenticated
  using (private.is_admin()) with check (private.is_admin());

create table if not exists public.club_repeat_requests (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  student_id uuid not null references public.app_users(id) on delete cascade,
  reason text not null check (reason in ('missed', 'full', 'again')),
  created_at timestamptz not null default now(),
  unique (club_id, student_id)
);
create index if not exists club_repeat_requests_club_idx on public.club_repeat_requests (club_id);
alter table public.club_repeat_requests enable row level security;
grant select, insert on public.club_repeat_requests to authenticated;
create policy club_repeat_requests_select on public.club_repeat_requests for select to authenticated
  using (student_id = (select auth.uid()) or private.is_admin());
create policy club_repeat_requests_insert on public.club_repeat_requests for insert to authenticated
  with check (student_id = (select auth.uid()));

create or replace function public.club_repeat_request_guard()
returns trigger language plpgsql set search_path = '' as $$
begin
  if not exists (
    select 1 from public.clubs c
    where c.id = new.club_id and c.type = 'insight' and c.status <> 'cancelled'
      and c.date + c.duration_minutes * interval '1 minute' < now()
  ) then
    raise exception 'Only previously held Insights can be requested again.';
  end if;
  return new;
end;
$$;
revoke all on function public.club_repeat_request_guard() from public, anon, authenticated;
create trigger club_repeat_request_guard_trg before insert on public.club_repeat_requests
  for each row execute function public.club_repeat_request_guard();
